---

- name: AVG | Adding i386 repositories
  command: dpkg --add-architecture i386
  become: yes

- name: AVG | Install dependencies
  apt:
    name: ['libc6-i386', 'libstdc++6']
    state: latest
  become: yes

# Link from http://free.avg.com/fr-fr/download-free-all-product
- name: AVG | Download Installer
  get_url:
    url: http://download.avgfree.com/filedir/inst/avg2013flx-r3118-a6926.i386.deb
    dest: /tmp/avg2013flx-r3118-a6926.i386.deb

- name: AVG | Install deb
  apt:
    deb: /tmp/avg2013flx-r3118-a6926.i386.deb
  become: yes
